
CREATE OR REPLACE STREAM DISTINCT_USER_STREAM (
    COGNITO_ID VARCHAR(64),
    DEVICE VARCHAR(32),
    OS VARCHAR(32),
    QUADRANT CHAR(1),
    DT TIMESTAMP);


CREATE OR REPLACE STREAM DESTINATION_SQL_STREAM (
    UNIQUE_USER_COUNT INT,
    ANDROID_COUNT INT,
    IOS_COUNT INT,
    WINDOWS_PHONE_COUNT INT,
    OTHER_OS_COUNT INT,
    QUADRANT_A_COUNT INT,
    QUADRANT_B_COUNT INT,
    QUADRANT_C_COUNT INT,
    QUADRANT_D_COUNT INT,
    WINDOW_TIME TIMESTAMP
  );


CREATE OR REPLACE PUMP "DISTINCT_USER_PUMP" AS
    INSERT INTO "DISTINCT_USER_STREAM"
        SELECT STREAM DISTINCT
          "cognitoId",
          "device",
          "os",
          "quadrant",
          FLOOR(s.ROWTIME to SECOND)
    FROM "SOURCE_SQL_STREAM_001" s;


CREATE OR REPLACE PUMP "OUTPUT_PUMP" AS
    INSERT INTO "DESTINATION_SQL_STREAM"
    SELECT STREAM
      COUNT(dus.COGNITO_ID) AS UNIQUE_USER_COUNT,
      COUNT((CASE WHEN dus.OS = 'Android' THEN COGNITO_ID ELSE null END)) AS ANDROID_COUNT,
      COUNT((CASE WHEN dus.OS = 'iOS' THEN COGNITO_ID ELSE null END)) AS IOS_COUNT,
      COUNT((CASE WHEN dus.OS = 'Windows Phone' THEN COGNITO_ID ELSE null END)) AS WINDOWS_PHONE_COUNT,
      COUNT((CASE WHEN dus.OS = 'other' THEN COGNITO_ID ELSE null END)) AS OTHER_OS_COUNT,
      COUNT((CASE WHEN dus.QUADRANT = 'A' THEN COGNITO_ID ELSE null END)) AS QUADRANT_A_COUNT,
      COUNT((CASE WHEN dus.QUADRANT = 'B' THEN COGNITO_ID ELSE null END)) AS QUADRANT_B_COUNT,
      COUNT((CASE WHEN dus.QUADRANT = 'C' THEN COGNITO_ID ELSE null END)) AS QUADRANT_C_COUNT,
      COUNT((CASE WHEN dus.QUADRANT = 'D' THEN COGNITO_ID ELSE null END)) AS QUADRANT_D_COUNT,
      ROWTIME as WINDOW_TIME
    FROM "DISTINCT_USER_STREAM" dus
    GROUP BY
      FLOOR (dus.ROWTIME TO SECOND);
